# Generated by Django 4.0.4 on 2022-09-23 05:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 9, 23, 12, 7, 7, 511315))),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
